inmobiliaria-add_DRF/inmobiliaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import first_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', first_view, name="inicio"),
    path("properties/", include("properties.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inmobiliaria-add_DRF/properties/urls.py
from django.urls import path
from .views import property_list_create, property_detail, property_update, property_delete

urlpatterns = [
    path('properties/', property_list_create, name="property_list_create"),
    path('properties/<int:pk>/', property_detail, name="property_detail"),
    path('properties/<int:pk>/edit/', property_update, name="property_update"),
    path('properties/<int:pk>/delete/', property_delete, name="property_delete"),
]

inmobiliaria-add_DRF/properties/models.py
from django.db import models
from users.models import User
import os.path
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile


class Property(models.Model):
    HOUSE = "house"
    DEPARTMENT = "deparment"
    LAND = "land"
    TYPE_PROPERTY = (
        (HOUSE, "Casa"),
        (DEPARTMENT, "Departamento"),
        (LAND, "Terreno"),
    )
    description = models.CharField(max_length=200, blank=True, null=True)
    street = models.CharField(max_length=100, blank=True, null=True)
    colony = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=6, blank=True, null=True)
    external_number = models.CharField(max_length=5, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    type = models.CharField(max_length=100, choices=TYPE_PROPERTY, blank=True, null=True)
    wide = models.FloatField(default=0)
    long = models.FloatField(default=0)
    ranking = models.IntegerField(default=0)
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="property_user",
        blank=True,
        null=True
    )
    thumbnail = models.ImageField(upload_to='thumbs', editable=False, blank=True, null=True)

    def __str__(self):
        return self.description

    # def save(self, *args, **kwargs):
    #
    #
    #     if not self.make_thumbnail():
    #         # set to a default thumbnail
    #         raise Exception('Could not create thumbnail - is the file type valid?')
    #
    #     super(Property, self).save(*args, **kwargs)

    def make_thumbnail(self):

        image = Image.open(self.image)
        thumbnail_size = 75, 75
        image.thumbnail(thumbnail_size)

        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()

        thumb_filename = thumb_name + '_thumb' + thumb_extension

        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False  # Unrecognized file type

        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)

        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()

        return True


class PropertyBuy(models.Model):
    buyer = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="propertybuy_user",
        blank=True,
        null=True
    )
    property = models.ForeignKey(
        Property,
        on_delete=models.PROTECT,
        related_name="propertybuy_user",
        blank=True,
        null=True
    )

    def __str__(self):
        return self.property.description

inmobiliaria-add_DRF/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    MALE = "male"
    FEMALE = "female"
    UNGENDER = "ungender"
    TYPE_GENDER=(
        (MALE, "Hombre"),
        (FEMALE, "Mujer"),
        (UNGENDER, "No definido"),
    )
    street = models.CharField(max_length=100, blank=True, null=True)
    colony = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=6, blank=True, null=True)
    external_number = models.CharField(max_length=5, blank=True, null=True)
    birth_day = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=20, choices=TYPE_GENDER, blank=True, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)

inmobiliaria-add_DRF/properties/forms.py
from django import forms
from .models import Property

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['description', 'street', 'colony', 'city', 'postal_code', 'external_number', 'price', 'type', 'wide', 'long', 'ranking', 'image', 'owner']

inmobiliaria-add_DRF/properties/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PropertyForm
from .models import Property
from django.contrib import messages

#Alumno : Edgar Perez Gomez S4C

# List and Create Properties
def property_list_create(request):
    if request.method == "POST":
        form = PropertyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Property created successfully!')
            return redirect('property_list_create')
    else:
        form = PropertyForm()
    
    properties = Property.objects.all()
    context = {
        "properties": properties,
        "form": form
    }
    return render(request, "properties/property_list.html", context=context)

# View Property Details
def property_detail(request, pk):
    property = get_object_or_404(Property, pk=pk)
    context = {
        "property": property
    }
    return render(request, "properties/property_detail.html", context=context)

# Update Property
def property_update(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == "POST":
        form = PropertyForm(request.POST, request.FILES, instance=property)
        if form.is_valid():
            form.save()
            messages.success(request, 'Property updated successfully!')
            return redirect('property_detail', pk=property.pk)
    else:
        form = PropertyForm(instance=property)
    
    context = {
        "form": form
    }
    return render(request, "properties/property_form.html", context=context)

# Delete Property
def property_delete(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == "POST":
        property.delete()
        messages.success(request, 'Property deleted successfully!')
        return redirect('property_list_create')
    
    context = {
        "property": property
    }
    return render(request, "properties/property_confirm_delete.html", context=context)

inmobiliaria-add_DRF/users/views.py
from django.shortcuts import render
from properties.models import Property
# Create your views here.


def first_view(request):
    properties = Property.objects.all()
    context = {
        "properties": properties
    }
    return render(request, "base.html", context=context)

inmobiliaria-add_DRF/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Album example · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">





<link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


  </head>
  <body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">

  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for property in properties %}
        <div class="col">
          <div class="card shadow-sm">
<!--            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>-->
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="http://127.0.0.1:8000/media/{{property.image}}">

            <div class="card-body">
              <p class="card-text">{{property.description}}.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.2/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

inmobiliaria-add_DRF/templates/properties/property_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Are you sure you want to delete "{{ property.description }}"?</h2>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
  <a href="{% url 'property_detail' property.pk %}">Cancel</a>
{% endblock %}

inmobiliaria-add_DRF/templates/properties/property_detail.html
{% extends 'base.html' %}
{% block content %}
  <h2>{{ property.description }}</h2>
  <p>{{ property.street }}, {{ property.colony }}, {{ property.city }}, {{ property.postal_code }}</p>
  <p>Price: {{ property.price }}</p>
  <p>Type: {{ property.get_type_display }}</p>
  <img src="{{ property.image.url }}" alt="{{ property.description }}">
  <p><a href="{% url 'property_update' property.pk %}">Edit</a></p>
  <form method="POST" action="{% url 'property_delete' property.pk %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'property_list_create' %}">Back to list</a>
{% endblock %}

inmobiliaria-add_DRF/templates/properties/property_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>{% if form.instance.pk %}Edit Property{% else %}New Property{% endif %}</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
  <a href="{% url 'property_list_create' %}">Cancel</a>
{% endblock %}

inmobiliaria-add_DRF/templates/properties/property_list.html
{% extends 'base.html' %}
{% block content %}
  <h2>{{ property.description }}</h2>
  <p>{{ property.street }}, {{ property.colony }}, {{ property.city }}, {{ property.postal_code }}</p>
  <p>Price: {{ property.price }}</p>
  <p>Type: {{ property.get_type_display }}</p>
  <img src="{{ property.image.url }}" alt="{{ property.description }}">
  <p><a href="{% url 'property_update' property.pk %}">Edit</a></p>
  <form method="POST" action="{% url 'property_delete' property.pk %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'property_list_create' %}">Back to list</a>
{% endblock %}